package game.map.editor.ui;

// all gui commands do one of the following:
// A: INVOKE an Editor method via an EditorEvent
// B: SHOW a dialog box of some kind that may in turn invoke some Editor method via an EditorEvent
public enum GuiCommand
{
	// 'File' menu items
	SAVE_MAP,
	OPEN_FILE,
	SAVE_AS,

	// import/export
	SAVE_OBJECTS,
	LOAD_OBJECTS,

	// 'Compile' menu items
	COMPILE_SHAPE,
	COMPILE_COLLISION,
	GENERATE_SCRIPT,

	// change selection mode
	SELECT_OBJECTS,
	SELECT_TRIANGLES,
	SELECT_VERTICES,
	SELECT_POINTS,

	// 'Selection' menu items
	SHOW_TRANSLATE_SELECTION_DIALOG,
	SHOW_ROTATE_SELECTION_DIALOG,
	SHOW_SCALE_SELECTION_DIALOG,
	SHOW_RESIZE_SELECTION_DIALOG,
	SHOW_FLIP_SELECTION_DIALOG,

	// additional buttons
	SHOW_CREATE_PRIMITIVE_MODEL_DIALOG,
	SHOW_CREATE_PRIMITIVE_COLLIDER_DIALOG,
	SHOW_CREATE_PRIMITIVE_ZONE_DIALOG,
	SHOW_CREATE_MODEL_FROM_DIALOG,
	SHOW_CREATE_COLLIDER_FROM_DIALOG,
	SHOW_CREATE_ZONE_FROM_DIALOG,
	SHOW_EXTRUDE_RIBBON_MODEL_DIALOG,
	SHOW_GENERATE_UV_DIALOG,
	SEPARATE_VERTS,
	FUSE_VERTS,
	CLEANUP_TRIS,
	JOIN_MODELS,
	SPLIT_MODEL,
	JOIN_COLLIDERS,
	SPLIT_COLLIDER,
	JOIN_ZONES,
	SPLIT_ZONE,
	SHOW_CREATE_MARKER_DIALOG,
	SHOW_CHOOSE_COLOR_DIALOG,
	SET_ALL_RENDER_MODE,

	CREATE_MODEL_GROUP,
	CREATE_COLLIDER_GROUP,
	CREATE_ZONE_GROUP,
	CREATE_MARKER_GROUP,

	CONVERT_COLLIDER_TO_ZONE,
	CONVERT_ZONE_TO_COLLIDER,
	CREATE_BVH,

	SELECT_ALL_WITH_TEXTURE,

	SHOW_SHORTCUTS,
	SHOW_EDITOR_PREFERENCES
}
